var images = {
  "SpadesA": require('./SpadesA.jpg'),
  "Spades2": require('./Spades2.jpg'),
  "Spades3": require('./Spades3.jpg'),
  "Spades4": require('./Spades4.jpg'),
  "Spades5": require('./Spades5.jpg'),
  "Spades6": require('./Spades6.jpg'),
  "Spades7": require('./Spades7.jpg'),
  "Spades8": require('./Spades8.jpg'),
  "Spades9": require('./Spades9.jpg'),
  "Spades10": require('./Spades10.jpg'),
  "SpadesJ": require('./SpadesJ.jpg'),
  "SpadesQ": require('./SpadesQ.jpg'),
  "SpadesK": require('./SpadesK.jpg'),

  "ClubsA": require('./ClubsA.jpg'),
  "Clubs2": require('./Clubs2.jpg'),
  "Clubs3": require('./Clubs3.jpg'),
  "Clubs4": require('./Clubs4.jpg'),
  "Clubs5": require('./Clubs5.jpg'),
  "Clubs6": require('./Clubs6.jpg'),
  "Clubs7": require('./Clubs7.jpg'),
  "Clubs8": require('./Clubs8.jpg'),
  "Clubs9": require('./Clubs9.jpg'),
  "Clubs10": require('./Clubs10.jpg'),
  "ClubsJ": require('./ClubsJ.jpg'),
  "ClubsQ": require('./ClubsQ.jpg'),
  "ClubsK": require('./ClubsK.jpg'),

  "DiamondsA": require('./DiamondsA.jpg'),
  "Diamonds2": require('./Diamonds2.jpg'),
  "Diamonds3": require('./Diamonds3.jpg'),
  "Diamonds4": require('./Diamonds4.jpg'),
  "Diamonds5": require('./Diamonds5.jpg'),
  "Diamonds6": require('./Diamonds6.jpg'),
  "Diamonds7": require('./Diamonds7.jpg'),
  "Diamonds8": require('./Diamonds8.jpg'),
  "Diamonds9": require('./Diamonds9.jpg'),
  "Diamonds10": require('./Diamonds10.jpg'),
  "DiamondsJ": require('./DiamondsJ.jpg'),
  "DiamondsQ": require('./DiamondsQ.jpg'),
  "DiamondsK": require('./DiamondsK.jpg'),

  "HeartsA": require('./HeartsA.jpg'),
  "Hearts2": require('./Hearts2.jpg'),
  "Hearts3": require('./Hearts3.jpg'),
  "Hearts4": require('./Hearts4.jpg'),
  "Hearts5": require('./Hearts5.jpg'),
  "Hearts6": require('./Hearts6.jpg'),
  "Hearts7": require('./Hearts7.jpg'),
  "Hearts8": require('./Hearts8.jpg'),
  "Hearts9": require('./Hearts9.jpg'),
  "Hearts10": require('./Hearts10.jpg'),
  "HeartsJ": require('./HeartsJ.jpg'),
  "HeartsQ": require('./HeartsQ.jpg'),
  "HeartsK": require('./HeartsK.jpg'),

  "LJ0": require('./LJ0.png'),
  "BJ0": require('./BJ0.png'),

  "back": require('./bk.jpg')
}
export default images;
