var images = {
  "SpadesA": require('./as.png'),
  "Spades2": require('./2s.png'),
  "Spades3": require('./3s.png'),
  "Spades4": require('./4s.png'),
  "Spades5": require('./5s.png'),
  "Spades6": require('./6s.png'),
  "Spades7": require('./7s.png'),
  "Spades8": require('./8s.png'),
  "Spades9": require('./9s.png'),
  "Spades10": require('./10s.png'),
  "SpadesJ": require('./js.png'),
  "SpadesQ": require('./qs.png'),
  "SpadesK": require('./ks.png'),

  "ClubsA": require('./ac.png'),
  "Clubs2": require('./2c.png'),
  "Clubs3": require('./3c.png'),
  "Clubs4": require('./4c.png'),
  "Clubs5": require('./5c.png'),
  "Clubs6": require('./6c.png'),
  "Clubs7": require('./7c.png'),
  "Clubs8": require('./8c.png'),
  "Clubs9": require('./9c.png'),
  "Clubs10": require('./10c.png'),
  "ClubsJ": require('./jc.png'),
  "ClubsQ": require('./qc.png'),
  "ClubsK": require('./kc.png'),

  "DiamondsA": require('./ad.png'),
  "Diamonds2": require('./2d.png'),
  "Diamonds3": require('./3d.png'),
  "Diamonds4": require('./4d.png'),
  "Diamonds5": require('./5d.png'),
  "Diamonds6": require('./6d.png'),
  "Diamonds7": require('./7d.png'),
  "Diamonds8": require('./8d.png'),
  "Diamonds9": require('./9d.png'),
  "Diamonds10": require('./10d.png'),
  "DiamondsJ": require('./jd.png'),
  "DiamondsQ": require('./qd.png'),
  "DiamondsK": require('./kd.png'),

  "HeartsA": require('./ah.png'),
  "Hearts2": require('./2h.png'),
  "Hearts3": require('./3h.png'),
  "Hearts4": require('./4h.png'),
  "Hearts5": require('./5h.png'),
  "Hearts6": require('./6h.png'),
  "Hearts7": require('./7h.png'),
  "Hearts8": require('./8h.png'),
  "Hearts9": require('./9h.png'),
  "Hearts10": require('./10h.png'),
  "HeartsJ": require('./jh.png'),
  "HeartsQ": require('./qh.png'),
  "HeartsK": require('./kh.png'),

  "back": require('./back.png')
}
export default images;
