var images = {
  "SpadesA": require('./SpadesA.png'),
  "Spades2": require('./Spades2.png'),
  "Spades3": require('./Spades3.png'),
  "Spades4": require('./Spades4.png'),
  "Spades5": require('./Spades5.png'),
  "Spades6": require('./Spades6.png'),
  "Spades7": require('./Spades7.png'),
  "Spades8": require('./Spades8.png'),
  "Spades9": require('./Spades9.png'),
  "Spades10": require('./Spades10.png'),
  "SpadesJ": require('./SpadesJ.png'),
  "SpadesQ": require('./SpadesQ.png'),
  "SpadesK": require('./SpadesK.png'),

  "ClubsA": require('./ClubsA.png'),
  "Clubs2": require('./Clubs2.png'),
  "Clubs3": require('./Clubs3.png'),
  "Clubs4": require('./Clubs4.png'),
  "Clubs5": require('./Clubs5.png'),
  "Clubs6": require('./Clubs6.png'),
  "Clubs7": require('./Clubs7.png'),
  "Clubs8": require('./Clubs8.png'),
  "Clubs9": require('./Clubs9.png'),
  "Clubs10": require('./Clubs10.png'),
  "ClubsJ": require('./ClubsJ.png'),
  "ClubsQ": require('./ClubsQ.png'),
  "ClubsK": require('./ClubsK.png'),

  "DiamondsA": require('./DiamondsA.png'),
  "Diamonds2": require('./Diamonds2.png'),
  "Diamonds3": require('./Diamonds3.png'),
  "Diamonds4": require('./Diamonds4.png'),
  "Diamonds5": require('./Diamonds5.png'),
  "Diamonds6": require('./Diamonds6.png'),
  "Diamonds7": require('./Diamonds7.png'),
  "Diamonds8": require('./Diamonds8.png'),
  "Diamonds9": require('./Diamonds9.png'),
  "Diamonds10": require('./Diamonds10.png'),
  "DiamondsJ": require('./DiamondsJ.png'),
  "DiamondsQ": require('./DiamondsQ.png'),
  "DiamondsK": require('./DiamondsK.png'),

  "HeartsA": require('./HeartsA.png'),
  "Hearts2": require('./Hearts2.png'),
  "Hearts3": require('./Hearts3.png'),
  "Hearts4": require('./Hearts4.png'),
  "Hearts5": require('./Hearts5.png'),
  "Hearts6": require('./Hearts6.png'),
  "Hearts7": require('./Hearts7.png'),
  "Hearts8": require('./Hearts8.png'),
  "Hearts9": require('./Hearts9.png'),
  "Hearts10": require('./Hearts10.png'),
  "HeartsJ": require('./HeartsJ.png'),
  "HeartsQ": require('./HeartsQ.png'),
  "HeartsK": require('./HeartsK.png'),

  "LJ0": require('./LJ0.png'),
  "BJ0": require('./BJ0.png'),

  "back": require('./bk.png')
}
export default images;
